apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath
  hostPath:
    path: /data/wp-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath
  resources:
    requests:
      storage: 5Gi
  volumeName: wp-data-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath
  hostPath:
    path: /data/mysql-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: hostpath
  resources:
    requests:
      storage: 5Gi
  volumeName: mysql-data-pv
